version: "3.9"
name: "event-service"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    command: air

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodata:
